#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# pppoe_reconfigure.sh
#
# Applies PPPoE credentials from pppoe.conf and reconnects — no interaction
# required.  Double-click this file in Nautilus to run it.
#
# Supports two methods (set PPPOE_METHOD in pppoe.conf):
#   pppd  — writes /etc/ppp/peers/<peer> + chap-secrets, uses pon/poff
#   nmcli — updates NetworkManager connection, uses nmcli up/down
#
# Requires: sudo privileges (asked once via pkexec or sudo)
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Re-launch inside a terminal if double-clicked from the file manager ──────
if [ ! -t 0 ]; then
    SELF="$(realpath "$0")"
    for TERM_EMU in gnome-terminal xterm konsole xfce4-terminal lxterminal; do
        if command -v "$TERM_EMU" &>/dev/null; then
            case "$TERM_EMU" in
                gnome-terminal) exec gnome-terminal -- bash "$SELF" ;;
                *)              exec "$TERM_EMU" -e "bash \"$SELF\"" ;;
            esac
        fi
    done
    # Absolute fallback — no known terminal found
    zenity --error --text="No terminal emulator found.\nInstall gnome-terminal or xterm." 2>/dev/null || true
    exit 1
fi

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; DIM='\033[2m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; }
die()     { error "$*"; echo; read -rp "Press Enter to close…"; exit 1; }
step()    { echo -e "\n${BOLD}$*${RESET}"; }

# ── Banner ───────────────────────────────────────────────────────────────────
echo -e "\n${BOLD}╔══════════════════════════════════╗"
echo -e "║   PPPoE Reconfigure              ║"
echo -e "╚══════════════════════════════════╝${RESET}\n"

# ── Load config ──────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF="$SCRIPT_DIR/pppoe.conf"

[ -f "$CONF" ] || die "Config file not found: $CONF"

# shellcheck source=pppoe.conf
source "$CONF"

# Validate required fields
[ -z "${PPPOE_IFACE:-}"    ] && die "PPPOE_IFACE is not set in pppoe.conf"
[ -z "${PPPOE_USERNAME:-}" ] && die "PPPOE_USERNAME is not set in pppoe.conf"
[ -z "${PPPOE_PASSWORD:-}" ] && die "PPPOE_PASSWORD is not set in pppoe.conf"
[ -z "${PPPOE_METHOD:-}"   ] && die "PPPOE_METHOD is not set in pppoe.conf"

# ── Check interface exists ───────────────────────────────────────────────────
if ! ip link show "$PPPOE_IFACE" &>/dev/null; then
    warn "Interface '$PPPOE_IFACE' not found.  Available interfaces:"
    ip -o link show | awk -F': ' '{print "  " $2}'
    die "Set PPPOE_IFACE to the correct interface in pppoe.conf."
fi

# ── Show current status ──────────────────────────────────────────────────────
step "Current connection status"
if ip addr show ppp0 &>/dev/null 2>&1; then
    PPP_IP=$(ip addr show ppp0 | awk '/inet /{print $2}' | cut -d/ -f1)
    info "ppp0 is UP  —  IP: ${PPP_IP:-unknown}"
else
    info "ppp0 is not active (no existing PPPoE session)"
fi

# ── Acquire sudo ─────────────────────────────────────────────────────────────
step "Requesting elevated privileges"
if ! sudo -v 2>/dev/null; then
    die "sudo authentication failed."
fi
success "sudo OK"

# ═════════════════════════════════════════════════════════════════════════════
# Method: pppd
# ═════════════════════════════════════════════════════════════════════════════
if [ "$PPPOE_METHOD" = "pppd" ]; then

    PEER="${PPPOE_PEER_NAME:-dsl-provider}"
    PEER_FILE="/etc/ppp/peers/$PEER"
    CHAP_FILE="/etc/ppp/chap-secrets"
    PAP_FILE="/etc/ppp/pap-secrets"

    # ── Write /etc/ppp/peers/<peer> ──────────────────────────────────────────
    step "Writing $PEER_FILE"
    sudo tee "$PEER_FILE" > /dev/null << EOF
# Generated by pppoe_reconfigure.sh — $(date)
noauth
plugin rp-pppoe.so $PPPOE_IFACE
name "$PPPOE_USERNAME"
usepeerdns
defaultroute
persist
hide-password
${PPPOE_EXTRA_OPTS:-}
EOF
    success "$PEER_FILE written"

    # ── Write credentials ────────────────────────────────────────────────────
    step "Writing PPP credentials"

    # Remove any existing entry for this username from both files, then append.
    for SECRETS_FILE in "$CHAP_FILE" "$PAP_FILE"; do
        if [ -f "$SECRETS_FILE" ]; then
            # Remove lines that contain this username
            sudo sed -i "/\"$PPPOE_USERNAME\"/d" "$SECRETS_FILE"
        else
            sudo touch "$SECRETS_FILE"
            sudo chmod 600 "$SECRETS_FILE"
        fi
        echo "\"$PPPOE_USERNAME\" * \"$PPPOE_PASSWORD\" *" | sudo tee -a "$SECRETS_FILE" > /dev/null
    done
    success "Credentials written to chap-secrets and pap-secrets"

    # ── Disconnect existing session ──────────────────────────────────────────
    step "Disconnecting existing PPPoE session"
    if ip link show ppp0 &>/dev/null 2>&1; then
        sudo poff "$PEER" 2>/dev/null || true
        # Wait for ppp0 to disappear (up to 8 s)
        for i in $(seq 1 8); do
            sleep 1
            ip link show ppp0 &>/dev/null 2>&1 || break
            echo -n "."
        done
        echo
        success "Disconnected"
    else
        info "No active session to disconnect"
    fi

    # ── Reconnect ────────────────────────────────────────────────────────────
    step "Connecting with new credentials"
    sudo pon "$PEER" || die "pon failed — check /var/log/syslog for pppd errors"

    # Wait for ppp0 to come up (up to 15 s)
    echo -n "Waiting for ppp0"
    for i in $(seq 1 15); do
        sleep 1
        echo -n "."
        if ip addr show ppp0 &>/dev/null 2>&1; then
            echo
            NEW_IP=$(ip addr show ppp0 | awk '/inet /{print $2}' | cut -d/ -f1)
            success "ppp0 is UP  —  new IP: ${NEW_IP:-unknown}"
            break
        fi
        if [ "$i" -eq 15 ]; then
            echo
            warn "ppp0 did not come up within 15 s"
            warn "Check logs: sudo journalctl -u pppd -n 30"
            warn "       or : sudo cat /var/log/syslog | grep pppd | tail -20"
        fi
    done

# ═════════════════════════════════════════════════════════════════════════════
# Method: nmcli
# ═════════════════════════════════════════════════════════════════════════════
elif [ "$PPPOE_METHOD" = "nmcli" ]; then

    NM_CONN="${PPPOE_NM_CONNECTION:-}"
    [ -z "$NM_CONN" ] && die "PPPOE_NM_CONNECTION is not set in pppoe.conf"

    command -v nmcli &>/dev/null || die "nmcli not found — is NetworkManager installed?"

    # Verify the connection exists
    if ! nmcli connection show "$NM_CONN" &>/dev/null; then
        warn "Connection '$NM_CONN' not found in NetworkManager."
        warn "Existing connections:"
        nmcli -t -f NAME connection show | sed 's/^/  /'
        die "Set PPPOE_NM_CONNECTION to the correct name in pppoe.conf."
    fi

    step "Updating NetworkManager credentials for '$NM_CONN'"
    sudo nmcli connection modify "$NM_CONN" \
        pppoe.username "$PPPOE_USERNAME" \
        pppoe.password "$PPPOE_PASSWORD"
    success "Credentials updated"

    step "Reconnecting"
    sudo nmcli connection down "$NM_CONN" 2>/dev/null || true
    sleep 2
    sudo nmcli connection up "$NM_CONN" || die "nmcli connection up failed"

    NEW_IP=$(nmcli -t -f IP4.ADDRESS connection show "$NM_CONN" 2>/dev/null | cut -d: -f2 | cut -d/ -f1)
    success "Connected  —  IP: ${NEW_IP:-unknown}"

else
    die "Unknown PPPOE_METHOD '$PPPOE_METHOD' — must be 'pppd' or 'nmcli'"
fi

# ── Done ─────────────────────────────────────────────────────────────────────
echo
echo -e "${GREEN}${BOLD}╔══════════════════════════════════╗"
echo -e "║   Reconfiguration complete!      ║"
echo -e "╚══════════════════════════════════╝${RESET}"
echo
echo -e "  Config  : ${DIM}$CONF${RESET}"
echo -e "  Method  : ${DIM}$PPPOE_METHOD${RESET}"
echo -e "  User    : ${DIM}$PPPOE_USERNAME${RESET}"
echo -e "  Iface   : ${DIM}$PPPOE_IFACE${RESET}"
echo

read -rp "Press Enter to close…"
